name: mlops_prod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - pip:
      - fsspec #removed specific version number due to cicd failure, let conda resolve
      - sympy==1.13.1
      - ray[train,serve,tune]==2.54.0
      - mlflow==2.15.0
      - great-expectations==1.15.1
      # 🚨 Pinned strictly to 0.7.21 to prevent future architectural breaking changes
      - evidently==0.7.21
      - fastapi
      - uvicorn
      - scikit-learn
      - pandas
      - python-dotenv
      - pytest