name: mlops_prod
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - fsspec==2024.6.1
      - sympy==1.13.1
      - ray[train,serve,tune]==2.54.0
      - mlflow==2.15.0
      - great-expectations==1.15.1
      - evidently>=0.5.0
      - fastapi
      - uvicorn
      - scikit-learn
      - pandas
      - python-dotenv
